import { createClient, type User } from '@supabase/supabase-js';
import './style.css';

const url = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;
const supabase = url && key ? createClient(url, key) : null;

type Employee = { id:string; employee_no:string|null; full_name:string; role:string|null; employment_type:string|null; status:string; phone:string|null; email:string|null };
type Task = { id:string; title:string; status:string; due_at:string|null; notes:string|null };

const root = document.querySelector<HTMLDivElement>('#root')!;
let user: User|null = null;
let companyId = localStorage.getItem('loge_company_id') || '';
let companyName = localStorage.getItem('loge_company_name') || '';
let section = 'dashboard';

function esc(v:string){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
function shell(body:string){root.innerHTML=`<div class="app"><aside><div class="brand">LOGE IT<span>Management System</span></div><div class="company">${esc(companyName||'Company')}</div><nav>${['dashboard','employees','attendance','tasks','leave','fuel','payroll','documents','audit'].map(x=>`<button class="nav ${section===x?'active':''}" data-section="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</nav><button id="logout" class="logout">Log out</button></aside><main><header><div><h1>${section==='dashboard'?'Dashboard':section[0].toUpperCase()+section.slice(1)}</h1><p>${esc(user?.email||'')}</p></div><div class="badge">Site Manager</div></header>${body}</main></div>`; document.querySelectorAll<HTMLButtonElement>('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section!;render()}); document.querySelector('#logout')?.addEventListener('click',async()=>{await supabase?.auth.signOut();localStorage.removeItem('loge_company_id');localStorage.removeItem('loge_company_name');user=null;render()});}
function loading(){root.innerHTML='<div class="center"><div class="card"><h2>LOGE IT</h2><p>Loading…</p></div></div>'}

async function render(){
 if(!supabase){root.innerHTML=`<div class="center"><div class="card"><div class="brand big">LOGE IT<span>Management System</span></div><h2>Connect your backend</h2><p>Copy <code>.env.example</code> to <code>.env</code> and add your Supabase project URL and anon key.</p><p>This build is designed for real authentication and database records; it does not use demo credentials.</p></div></div>`;return;}
 if(!user){auth();return;} if(!companyId){companySetup();return;}
 if(section==='dashboard') dashboard(); else if(section==='employees') employees(); else if(section==='tasks') tasks(); else if(section==='attendance') attendance(); else if(section==='leave') simple('Leave','Employee leave requests will appear here once connected.'); else if(section==='fuel') simple('Fuel & Accounts','Fuel transactions and account customers are stored in the production database.'); else if(section==='payroll') simple('Payroll','Payroll runs and items are stored in the production database.'); else if(section==='documents') simple('Documents','Use private Supabase Storage for employee and company documents.'); else audit();
}
function auth(){root.innerHTML=`<div class="center"><form id="auth" class="card auth"><div class="brand big">LOGE IT<span>Management System</span></div><h2>Sign in</h2><label>Email<input id="email" type="email" required autocomplete="email"></label><label>Password<input id="password" type="password" required autocomplete="current-password"></label><button class="primary">Log in</button><p id="msg" class="muted">Use your LOGE IT account.</p></form></div>`;document.querySelector<HTMLFormElement>('#auth')!.onsubmit=async e=>{e.preventDefault();const email=(document.querySelector('#email') as HTMLInputElement).value;const password=(document.querySelector('#password') as HTMLInputElement).value;const {data,error}=await supabase!.auth.signInWithPassword({email,password});if(error){(document.querySelector('#msg')!).textContent=error.message;return;}user=data.user;render()};}
function companySetup(){root.innerHTML=`<div class="center"><form id="company" class="card"><div class="brand big">LOGE IT<span>Management System</span></div><h2>Select company</h2><p class="muted">Enter the company code assigned to your LOGE IT account.</p><label>Company code<input id="code" required placeholder="e.g. MBT-BOSVELD"></label><button class="primary">Continue</button><p id="msg" class="muted"></p></form></div>`;document.querySelector<HTMLFormElement>('#company')!.onsubmit=async e=>{e.preventDefault();const code=(document.querySelector('#code') as HTMLInputElement).value.trim().toUpperCase();const {data,error}=await supabase!.from('companies').select('id,name').eq('company_code',code).single();if(error){document.querySelector('#msg')!.textContent='Company not found or not accessible.';return;}const m=await supabase!.from('memberships').select('role,active').eq('company_id',data.id).eq('user_id',user!.id).eq('active',true).single();if(m.error){document.querySelector('#msg')!.textContent='Your account is not a member of this company.';return;}companyId=data.id;companyName=data.name;localStorage.setItem('loge_company_id',companyId);localStorage.setItem('loge_company_name',companyName);render()};}
async function dashboard(){const [e,t,a,l]=await Promise.all([supabase!.from('employees').select('id,status',{count:'exact',head:true}).eq('company_id',companyId),supabase!.from('tasks').select('id,status',{count:'exact',head:true}).eq('company_id',companyId).neq('status','completed'),supabase!.from('attendance').select('id',{count:'exact',head:true}).eq('company_id',companyId).eq('work_date',new Date().toISOString().slice(0,10)),supabase!.from('leave_requests').select('id',{count:'exact',head:true}).eq('company_id',companyId).eq('status','pending')]);shell(`<div class="grid cards"><div class="metric"><span>Employees</span><b>${e.count??0}</b></div><div class="metric"><span>Open tasks</span><b>${t.count??0}</b></div><div class="metric"><span>Attendance today</span><b>${a.count??0}</b></div><div class="metric"><span>Pending leave</span><b>${l.count??0}</b></div></div><div class="card"><h2>Needs attention</h2><div class="list"><div>Pending leave requests <b>${l.count??0}</b></div><div>Open manager tasks <b>${t.count??0}</b></div></div></div>`)}
async function employees(){const {data,error}=await supabase!.from('employees').select('id,employee_no,full_name,role,employment_type,status,phone,email').eq('company_id',companyId).order('full_name');shell(`<div class="toolbar"><button id="addEmp" class="primary">+ Add employee</button></div><div class="card"><h2>Employees</h2>${error?`<p class="error">${esc(error.message)}</p>`:`<table><thead><tr><th>No.</th><th>Name</th><th>Role</th><th>Type</th><th>Status</th></tr></thead><tbody>${(data as Employee[]).map(x=>`<tr><td>${esc(x.employee_no||'—')}</td><td>${esc(x.full_name)}</td><td>${esc(x.role||'—')}</td><td>${esc(x.employment_type||'—')}</td><td>${esc(x.status)}</td></tr>`).join('')}</tbody></table>`}</div>`);document.querySelector('#addEmp')?.addEventListener('click',()=>addEmployee())}
async function addEmployee(){const name=prompt('Employee full name');if(!name)return;const role=prompt('Role')||'';const {error}=await supabase!.from('employees').insert({company_id:companyId,full_name:name,role,status:'active'});if(error)alert(error.message);else render()}
async function tasks(){const {data,error}=await supabase!.from('tasks').select('id,title,status,due_at,notes').eq('company_id',companyId).order('due_at',{ascending:true,nullsFirst:false});shell(`<div class="toolbar"><button id="addTask" class="primary">+ Add task</button></div><div class="card"><h2>Manager tasks</h2>${error?`<p class="error">${esc(error.message)}</p>`:(data as Task[]).map(t=>`<div class="task"><div><b>${esc(t.title)}</b><small>${t.due_at?new Date(t.due_at).toLocaleString():'No due date'}</small></div><span class="status">${esc(t.status)}</span></div>`).join('')||'<p class="muted">No tasks yet.</p>'}</div>`);document.querySelector('#addTask')?.addEventListener('click',addTask)}
async function addTask(){const title=prompt('Task title');if(!title)return;const {error}=await supabase!.from('tasks').insert({company_id:companyId,title,status:'open'});if(error)alert(error.message);else render()}
async function attendance(){const date=new Date().toISOString().slice(0,10);const {data,error}=await supabase!.from('attendance').select('id,employee_id,clock_in,lunch_out,lunch_in,clock_out,status,overtime_minutes').eq('company_id',companyId).eq('work_date',date);shell(`<div class="card"><h2>Attendance — ${date}</h2>${error?`<p class="error">${esc(error.message)}</p>`:`<table><thead><tr><th>Employee</th><th>Clock in</th><th>Lunch</th><th>Clock out</th><th>Status</th></tr></thead><tbody>${(data||[]).map((x:any)=>`<tr><td>${esc(x.employee_id)}</td><td>${x.clock_in?'✓':'—'}</td><td>${x.lunch_out?'Out':'—'}${x.lunch_in?' / Back':''}</td><td>${x.clock_out?'✓':'—'}</td><td>${esc(x.status)}</td></tr>`).join('')}</tbody></table>`}</div>`)}
function simple(title:string,text:string){shell(`<div class="card"><h2>${title}</h2><p>${text}</p><p class="muted">The navigation is wired to the same company-scoped database foundation. We can build this module next without replacing the app.</p></div>`)}
async function audit(){const {data,error}=await supabase!.from('audit_logs').select('action,entity_type,created_at').eq('company_id',companyId).order('created_at',{ascending:false}).limit(100);shell(`<div class="card"><h2>Audit log</h2>${error?`<p class="error">${esc(error.message)}</p>`:`<table><thead><tr><th>Time</th><th>Action</th><th>Record</th></tr></thead><tbody>${(data||[]).map((x:any)=>`<tr><td>${new Date(x.created_at).toLocaleString()}</td><td>${esc(x.action)}</td><td>${esc(x.entity_type||'—')}</td></tr>`).join('')||'<tr><td colspan="3">No audit entries yet.</td></tr>'}</tbody></table>`}</div>`)}

(async()=>{loading(); if(supabase){const {data}=await supabase.auth.getSession();user=data.session?.user||null;supabase.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;render()});} render();})();
